---

 - name: Playbook no 2
   hosts: webservers
   become: true
   tasks:

   - name: Install nginx
     apt:
      name: nginx
      state: present

   - name: Start nginx
     service:
      name: nginx
      enabled: true
      state: started

   - name: Clone git repository
     git:
      repo: https://github.com/msajidaligik/gik-fcse-icet2022.git
      dest: ~/icet2022

   - name: Copy repository to nginx root
     shell: mv ~/icet2022/* /var/www/html/

   - name: Restart nginx
     service:
      name: nginx
      state: restarted
